name: Test pipeline

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  test-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.5

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dbx
        run: |
          pip install dbx
          
      - name: Deploy unit/integration test
        run: |
          dbx deploy --jobs=cicd-azdevops-scala-notebook-test --files-only    

      - name: Run unit/integration test
        run: |
          dbx launch --job=cicd-azdevops-scala-notebook-test --as-run-submit --trace



